services:
  postgres:
    # Compose automatically detects the .env file. We can pass here a .env.test, or leave it as it is
    env_file:
      - ./.env
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend:
    env_file:
      - ./.env
    volumes:
    - ./symcomp-server:/app
    entrypoint: ["/bin/sh", "/app/entrypoint-test.sh"]
    
  
  frontend:
    env_file:
        - ./.env
    build:
      target: development
    volumes:
    - ./symcomp:/app
    command: echo "testing frontend?"

#Ensures our development database isnt impacted
volumes:
  postgres_test_data: