services:
  postgres:
    # Compose automatically detects the .env file, which is not the one we want (possibly?)
    env_file:
      - ./.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend:
    env_file:
      - ./.env.test
    entrypoint: ["/bin/sh", "/app/entrypoint-test.sh"]
  
  frontend:
    env_file:
        - ./.env.test
    build:
      target: development
    command: echo "testing frontend?"

volumes:
  postgres_test_data: