services:
  postgres:
    ports:
      - "5432:5432"
  
  backend:
    build:
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./symcomp-server:/app
    ports:
      - "8000:8000"
    
  frontend:
    build:
      target: development
    volumes:
      - ./symcomp:/app
      - /app/node_modules
    ports:
      - "3000:3000"