services:
  symcomp-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-nextjs
    container_name: app-nextjs-container
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    restart: unless-stopped
